CREATE TABLE PUPILS_DATA (ROLL_NUMBER INT  PRIMARY KEY, NAME VARCHAR(35), ADDRESS VARCHAR(50))
CREATE TABLE PUPILS_RESULTS_DATA (ROLL_NUMBER INT , MATHS_MARKS INT, SCIENCE_MARKS INT, TOTAL_MARKS INT, FOREIGN_KEY ROLL_NUMBER REFERENCES PUPILS_DATA ROLL_NUMBER )

CREATE TABLE PUPILS_DATA (ROLL_NUMBER INT PRIMARY KEY, NAME VARCHAR(35), ADDRESS VARCHAR(50))
CREATE TABLE PUPILS_RESULTS_DATA (ROLL_NUMBER INT PRIMARY KEY, MATHS_MARKS INT, SCIENCE_MARKS INT, TOTAL_MARKS INT)

ALTER TABLE PUPILS_DATA MODIFY COLUMN ROLL_NUMBER INT NOT NULL DEFAULT AUTO_INCREMENT=1
-- ALTER TABLE PUPILS_RESULTS_DATA MODIFY ROLL_NUMBER INT NOT NULL DEFAULT 0
SELECT * FROM PUPILS_DATA
SELECT * FROM PUPILS_RESULTS_DATA

drop table pupils_data
DROP TABLE pupils_results_data